###
GET http://localhost:8081/api/database/current

###
GET http://localhost:8081/api/database/data

###
PUT http://localhost:8081/api/database/switch/primary

###
PUT http://localhost:8081/api/database/switch/secondary

###
POST http://localhost:8081/api/database/stop